# CloudFormation file
Description: Resources implementing the corner tables

Resources:

  AuthTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: auth
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: authId
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: authId
          KeyType: HASH
      GlobalSecondaryIndexes: 
        - IndexName: userId-index
          KeySchema: 
            - AttributeName: userId
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: users
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: username
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      GlobalSecondaryIndexes: 
        - IndexName: username-index
          KeySchema: 
            - AttributeName: username
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  InvitesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: invites
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: email
          KeyType: HASH
